### ISSUE TITLE
💡 [FEATURE] - Search bar for projects page

### ISSUE THREAD

**Issue by akash0708** [Pinaka-Pani-18/Public-Codebases#14]
Add a search bar for the projects page. The frontend of the search bar has been created till now, will work on the backend part after creating data.json. Since the project name has now been changed, can I know what the end goal of this project is? Will it consume the GitHub API or will people manually add GitHub links of the projects?

**Comment by akash0708** [comment]
@Pinaka-Pani-18 add the labels, the search bar frontend is ready will open a PR as soon as the labels are added.

**Comment by Pinaka-Pani-18** [comment]
> Add a search bar for the projects page. The frontend of the search bar has been created till now, will work on the backend part after creating data.json. Since the project name has now been changed, can I know what the end goal of this project is? Will it consume the GitHub API or will people manually add GitHub links of the projects?

The people will manually add open source projects to the list
