### ISSUE TITLE
💡 [FEATURE] - Create a Design for Home Page using Figma

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#16]
**Description:**
Create a user interface (UI) for the home page of our public codebases website.

**Tasks:**
- [ ] Design the UI for the home page using Figma.

**Comment by eshita241** [comment]
can you please assign me this?

**Comment by Pinaka-Pani-18** [comment]
> can you please assign me this?

Assigned @eshita241, you can start working on it.

**Comment by eshita241** [comment]
the design is done
how do you want me to share it?

**Comment by Pinaka-Pani-18** [comment]
> the design is done how do you want me to share it?

For now, please share the link here so I can review it. After that, you can create a PR, and I will guide you on the exact place to add it.

**Comment by eshita241** [comment]
https://www.figma.com/file/M1LU8jeckUflI7qOUmNLYz/PUBLIC-CODEBASES?type=design&node-id=0%3A1&mode=design&t=Dcuvg2iptfe15Ypn-1

**Comment by eshita241** [comment]
did you go through it?

**Comment by Pinaka-Pani-18** [comment]
> did you go through it?

Yes, it looks good, but we need another two subsections as well.

![Screenshot_2023-10-27-02-18-26-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Pinaka-Pani-18/Public-Codebases/assets/102857774/417a6fee-db06-44e3-9857-3f493cc0f09d)

Use the same text and buttons as above for other two sections.

**Comment by eshita241** [comment]
https://www.figma.com/file/M1LU8jeckUflI7qOUmNLYz/PUBLIC-CODEBASES?type=design&node-id=0%3A1&mode=design&t=fD37wuHUJQuyYys1-1
here is the design with suggested changes.

**Comment by eshita241** [comment]
please respond

**Comment by Pinaka-Pani-18** [comment]
> please respond

I apologize for the late response, @eshita241. It looks good now. Let's create a PR by adding the link to the readme.md file below the "Community" header, under a new header called "Future Designs." For the subheading, use "Header" and paste the link there.

**Comment by eshita241** [comment]
its okay, i have made the PR, please check
