### ISSUE TITLE
💡 [FEATURE] - Create a Design for Contributors Page using Figma

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#18]
**Description:**
While the current contributors page is functional, we aim to make it more creative. Create a user interface (UI) for the contributors page of our public codebases website.

**Tasks:**
- [ ] Design the UI for the contributors page using Figma.

**Comment by eshita241** [comment]
please assign me this issue.

**Comment by eshita241** [comment]
please reply.

**Comment by eshita241** [comment]
https://www.figma.com/file/M1LU8jeckUflI7qOUmNLYz/PUBLIC-CODEBASES?type=design&node-id=0%3A1&mode=design&t=ZKHaEDGkMI7RzpHX-1
here is the link to the design file with the suggested options.

**Comment by eshita241** [comment]
did you go through the file?
