### ISSUE TITLE
🐛 [BUG] - Fix the Title in Navbar

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#19]
**Description:**
The font is applied across the website, but the project title in the navbar does not have the font applied.

**Tasks:**
- [ ] Resolve the issue with the font not being applied to the project title in the navbar.

**Comment by kenjo09** [comment]
can i take this issue as my first contrib

**Comment by Pinaka-Pani-18** [comment]
> can i take this issue as my first contrib

Assigned to you @kenjo09 , you can start working on it.

**Comment by kenjo09** [comment]
@Pinaka-Pani-18 just want to double check on you. the "font-poppin" is already applied on the nav bar. can you give further info for this as it is vague.

<img width="1701" alt="image" src="https://github.com/Pinaka-Pani-18/Public-Codebases/assets/29970114/13b74610-166c-422d-bc24-8a8e9a79c98c">

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 just want to double check on you. the "font-poppin" is already applied on the nav bar. can you give further info for this as it is vague.
> <img alt="image" width="1701" src="https://user-images.githubusercontent.com/29970114/275953920-13b74610-166c-422d-bc24-8a8e9a79c98c.png">

but why the font of title is different from others ?

**Comment by kenjo09** [comment]
the title has a font style of "bold" thats why its different from "home/projects/contributors"

**Comment by Pinaka-Pani-18** [comment]
> the title has a font style of "bold" thats why its different from "home/projects/contributors"

Alright, if that's the problem, can we resolve it by adjusting the font or making other changes to ensure that the title matches the font used for other elements?

**Comment by kenjo09** [comment]
submitted a pull request this - other title uses the same styling as the others
