### ISSUE TITLE
✨ [ENHANCEMENT] - Search Bar and Implement Project Filtering

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#24]
**Description:**
Enhance the search bar and write the code for filtering the projects.

**Tasks:**
- Make the search bar responsive.
- write code for a search filter so that when someone searches for a project by name, it displays the matching projects.

**Comment by Diwanshumidha** [comment]
I can work on this Feature

**Comment by Pinaka-Pani-18** [comment]
> I can work on this Feature

Assigned to you @Diwanshumidha, you can start working on it.

**Comment by Pinaka-Pani-18** [comment]
@Diwanshumidha any update ?

**Comment by Diwanshumidha** [comment]
Search functionality is completed

**Comment by Diwanshumidha** [comment]
Is there any problem
