### ISSUE TITLE
🐛 [BUG] - Change the github links in the navbar and footer

### ISSUE THREAD

**Issue by Sh4dab** [Pinaka-Pani-18/Public-Codebases#26]
**Describe the Bug**

The Github link in navbar is of previous repo and in the footer also all the links are of previous repo.

**Expected Behavior**
The link should be replaced from this repo link.

**Actual Behavior**

A clear and concise description of what actually happened.

**Screenshots**

**Additional Context**

**Possible Solution**

(Optional) If you have a possible solution or workaround for the bug, please describe it.

**Your Environment**

- Browser/OS: [e.g., Chrome/Windows]
- Version: [e.g., 22]

**Labels**

Please add appropriate labels to this issue: `bug`, `needs-triage`, etc.

**Comment by Pinaka-Pani-18** [comment]
@Sh4dab assigned to you, you can start working on this issue.
