### ISSUE TITLE
🐛 [BUG] - workflow for greeting new contributors

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#3]
### Description

The workflow is not functioning correctly when a new contributor raises their first issue or PR.

This is how it is being displayed:
![Screenshot 2023-10-14 102153](https://github.com/Pinaka-Pani-18/Hacktoberfest-Projects-Hub/assets/102857774/bab37398-ea4a-431d-90f5-4ba48cbe12e2)

**Tasks:**
- [ ] Examine the workflow configuration and identify the root cause of the problem. Make necessary adjustments to ensure it works as expected.

**Comment by A-5ingh** [comment]
Can you reopen the #11 that will fix the issue with workflow?

**Comment by Pinaka-Pani-18** [comment]
> Can you reopen the #11 that will fix the issue with workflow?

Hi @A-5ingh, can you please Create a separate PR again.
