### ISSUE TITLE
✨ [ENHANCEMENT] - Improve the Project page

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#4]
**Description:**

Improve the project page.

**Tasks:**
- [ ] Create a dummy array or .json and map all the data, making it easy for others to add their projects.
- [ ] Enhance the user interface (UI).

**Comment by Honey2339** [comment]
Interesting i would like to contribute

**Comment by akash0708** [comment]
@Pinaka-Pani-18 , tell me what changes you are looking for in the UI. Working on the json part

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 , tell me what changes you are looking for in the UI. Working on the json part

Are you able to add No of forks beside the stars ? If possible add it.

**Comment by Pinaka-Pani-18** [comment]
any update @akash0708 ?
