### ISSUE TITLE
📄 [DOCS] - Improve ReadMe.md file

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#7]
**Description:**

Improve the `readme.md` file.

**Tasks:**

- [ ] Update the table of contents to include the following sections:
    - Tech Stack Used
    - Installation Guide
    - Contributing Guidelines
    - Community
    - License
    - Finally, add a message: "If you enjoy contributing to our project, please consider giving it a star. Happy open-source contributions!"
- [ ] Show all the contributors by thanking them.

**Comment by Ajiboso-Adeola** [comment]
Hi 👋, I would like to work on this issue, could you please assign it to me

**Comment by Pinaka-Pani-18** [comment]
> Hi 👋, I would like to work on this issue, could you please assign it to me

Assigned to you @Ajiboso-Adeola, start working on it.

**Comment by Pinaka-Pani-18** [comment]
@Ajiboso-Adeola any updates ?

**Comment by Ajiboso-Adeola** [comment]
I'm on it

**Comment by Ajiboso-Adeola** [comment]
> I'm on it
Done, kindly review the PR

**Comment by Pinaka-Pani-18** [comment]
Hi @Ajiboso-Adeola ,

This is another one of my open-source projects, [Contributors-Gallery](https://github.com/Pinaka-Pani-18/Contributors-Gallery). Can you help improve the readme.md file for this project as well?

If you can do, please create an issue, and once assigned, you can make a PR.

**Comment by Ajiboso-Adeola** [comment]
> Hi @Ajiboso-Adeola ,
> 
> This is another one of my open-source projects, [Contributors-Gallery](https://github.com/Pinaka-Pani-18/Contributors-Gallery). Can you help improve the readme.md file for this project as well?
> 
> If you can do, please create an issue, and once assigned, you can make a PR.

Sure, will check it out
