### ISSUE TITLE
✨ [ENHANCEMENT] - Improving the ISSUE Templates

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Public-Codebases#8]
**Description**
We already have some issue templates in place, but we need to make it easier for contributors to raise issues. To achieve this, we are planning to enhance all the issue templates.

**Tasks**
For each individual issue template, the enhancement includes:
-  Description field.
-  Including a screenshot field(if applicable).
-  Implementing a task bar for contributors to express their willingness to work on the issue.
-  Additional information field.

**Comment by Shashankpantiitbhilai** [comment]
Assign it to me,I am interested

**Comment by Pinaka-Pani-18** [comment]
any updates @Shashankpantiitbhilai ?

**Comment by Keith-Web3** [comment]
Hello, I see no one is assigned to this. Can I work on the issue?
